services:
  mariadb:
    image: mariadb:11.7.2
    container_name: mariadb-countries-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: countries_data
      MYSQL_USER: root
    ports:
      - '3321:3306'
    volumes:
      - mariadb-countries-data:/var/lib/mysql
    networks:
      - internal-net
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: redis-countries-dev
    restart: unless-stopped
    ports:
      - '6321:6379'
    networks:
      - internal-net
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  mariadb-countries-data:

networks:
  internal-net:
    external: true
