# Define a reusable template for all our Node.js apps
x-app-template: &app-template
  image: node:22-alpine
  restart: unless-stopped
  working_dir: /repo
  environment:
    - NODE_ENV=development
  volumes:
    - ./:/repo
    - /repo/node_modules
  networks:
    - internal-net
  healthcheck:
    test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
    interval: 30s
    timeout: 5s
    retries: 3

services:
  mariadb:
    image: mariadb:11.7.2
    container_name: mariadb-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mariadb_data
      MYSQL_USER: root
    ports:
      - '3321:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - internal-net
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: redis-dev
    restart: unless-stopped
    ports:
      - '6321:6379'
    networks:
      - internal-net
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 5s
      retries: 3

  neighborly-service:
    <<: *app-template
    container_name: neighborly-service-dev
    env_file:
      - ./apps/neighborly/.env
    ports:
      - '3023:3000'
    command: pnpm nx serve neighborly-service

  countries-service:
    <<: *app-template
    container_name: countries-service-dev
    env_file:
      - ./apps/countries/.env
    ports:
      - '3024:3000'
    command: pnpm nx serve countries-service

  indicators-service:
    <<: *app-template
    container_name: indicators-service-dev
    env_file:
      - ./apps/indicators/.env
    ports:
      - '3025:3000'
    command: pnpm nx serve indicators-service

volumes:
  mariadb-data:

networks:
  internal-net:
    external: true
