services:
  indicators-service:
    build:
      context: ../..
      dockerfile: infrastructure/Dockerfile
      args:
        APP_PATH: apps/indicators
    container_name: indicators-service
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=production
      - DB_HOST=${INDICATORS_DB_HOST}
      - DB_PORT=${INDICATORS_DB_PORT}
      - DB_NAME=${INDICATORS_DB_NAME}
      - DB_USER=${INDICATORS_DB_USER}
      - DB_PASSWORD=${INDICATORS_DB_PASSWORD}
      - REDIS_HOST=${INDICATORS_REDIS_HOST}
      - REDIS_PORT=${INDICATORS_REDIS_PORT}
    expose:
      - 3000
    networks:
      - internal-net
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  internal-net:
    external: true
